# Generated by Django 3.1.7 on 2021-06-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('cheese_type', models.CharField(choices=[('Моцарелла', 'Моцарелла'), ('Блючиз', 'Блючиз'), ('Чеддер', 'Чеддер'), ('Пармезан', 'Пармезан')], default='Моцарелла', max_length=20, verbose_name='Вид Сыра')),
                ('dough_thickness', models.CharField(choices=[('Тонкое тесто', 'Тонкое тесто'), ('Традиционное тесто', 'Традиционное тесто')], default='Тонкое тесто', max_length=20, verbose_name='Толщина Теста')),
                ('secret_ingredient', models.CharField(blank=True, max_length=255, null=True, verbose_name='Секретный Ингредиент')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Пиццы',
            },
        ),
    ]
